cc_library(
  name = "row",
  srcs = ["row.cpp"],
  hdrs = ["row.h"],
  visibility = ["//visibility:public"],
)
cc_test(
  name = "row_test",
  size = "small",
  srcs = ["row_test.cpp"],
  deps = ["@com_google_googletest//:gtest_main", ":row"],
    visibility = ["//visibility:public"],
)